# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=leetup

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - set -e
  - rustup self update
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt -y install pkg-config libssl-dev ; fi

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: bI276vaf4diS5GgFwVtP3J+f/P2f4H2+xwU6wC7Hj4UkRl5eYfKoIx62HCj1684pNxNAIeGVqjyXTir1LnaDNK1tGdfVDS22u5d83rpONqApk7CUMlW9tocNSfcnlEwlQa5BLIvk1fdsG4hx1nK7qQYEMo6k4D/BOLai1NtVZpswYVqDDOpKF7Ytv1l8UiyR4gez8l6aqzNcsgIsD4kDFK0282xqVkf5GXMh1qLY2RTnq2jRPqMaZncNKSjdv610gJxiPZ2BUfO0vgGdftfGaM7wo6gTRB0kmdchs40qpOKOx+L9s/HQVXzyMD2PZ9QHBqjyi18ub6E67eIlcnaJh/5klIqGbdZYHQIat+CVl3FD/gcKrA2NKKDhgJN565GiwMfzG6XM3k2n1irMntkuwfroD5m6bpcnNl0HpGRLMiiXF3peCjlXt9MayuC+/N+RAup2PTenonnvp6FXYvhk6N+wlFgXfRcZ3t4cR1PHGHv3fTDNMxgTc7Z4OQRkCOug2UQFUCbEOWGrODeR9uS+6AVM0P6YiFLbU+9mcqqn+5moYCIcnIl4/BUYNqfW1wLI3X3bbPndINCsrcsJRjt8Pf1a7jE3yMfITayKle0Jsn8h1GS/qzjVDLfpfKLYhYzfEIvN4DwwiYMpngmEEy242Y1tKRW3MZq7NGR3Q+5tcwk=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
