name: Rust

on:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: leetup
            asset_name: leetup${{ env.RELEASE_VERSION }}-linux-amd64.sh
          - os: windows-latest
            artifact_name: leetup.exe
            asset_name: leetup${{ env.RELEASE_VERSION }}-windows-amd64.exe
          - os: macos-latest
            artifact_name: leetup
            asset_name: leetup${{ env.RELEASE_VERSION }}-macos-amd64.sh
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
